name: karamtrade
description: منصة ذكاء اصطناعي وتعليم ومسابقات أسبوعية مطورة من تصميم كرم.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.10.0
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.7.0
  google_sign_in: ^6.1.0
  provider: ^6.0.5
  flutter_spinkit: ^5.2.0
  font_awesome_flutter: ^10.4.0
  http: ^1.2.0
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/icons/
